const seed=[['لمبة LED 12W','10000001',35,55,80,'لمبات'],['كابل نحاس 2.5 مم','10000002',120,175,35,'كابلات'],['مفتاح مفرد','10000003',18,30,120,'مفاتيح'],['بريزة مزدوجة','10000004',28,45,75,'برايز'],['قاطع 16 أمبير','10000005',65,90,30,'قواطع']];
const K={p:'fs_products',c:'fs_customers',s:'fs_sales',e:'fs_expenses',u:'fs_users'},$=id=>document.getElementById(id),money=n=>(+n||0).toFixed(2),esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const read=(k,d)=>JSON.parse(localStorage.getItem(k)||'null')??d;let products=read(K.p,seed.map((x,i)=>({id:i+1,name:x[0],barcode:x[1],buy:x[2],sell:x[3],qty:x[4],min:10,cat:x[5]}))),customers=read(K.c,[]),sales=read(K.s,[]),expenses=read(K.e,[]),users=read(K.u,[{id:1,name:'admin',role:'مدير',pass:'FiveStars@2026'}]),cart=[];
if(!users.some(u=>u.name==='admin'))users.unshift({id:1,name:'admin',role:'مدير',pass:'FiveStars@2026'});else{const a=users.find(u=>u.name==='admin');if(!a.pass)a.pass='FiveStars@2026'}
function save(){Object.entries({[K.p]:products,[K.c]:customers,[K.s]:sales,[K.e]:expenses,[K.u]:users}).forEach(([k,v])=>localStorage.setItem(k,JSON.stringify(v)))}save();
function toast(m){let t=$('toast');t.textContent=m;t.style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>t.style.display='none',1800)}
function addCart(id){let p=products.find(x=>x.id==id);if(!p||p.qty<1)return toast('الصنف غير متاح');let x=cart.find(x=>x.id==id);if(x){if(x.qty>=p.qty)return toast('الكمية غير كافية');x.qty++}else cart.push({id:p.id,qty:1});renderCart()}
function scan(code,mode){code=String(code||'').trim();if(!code)return;let p=products.find(x=>x.barcode===code);if(mode==='pos'){p?addCart(p.id):toast('الباركود غير مسجل');$('posBarcode').value='';$('posBarcode').focus()}else{$('pBarcode').value=code;toast('تم التقاط الباركود')}}
function renderProducts(){let q=($('posSearch').value||'').toLowerCase(),a=products.filter(p=>(p.name+' '+p.barcode+' '+p.cat).toLowerCase().includes(q));$('products').innerHTML=a.map(p=>`<button class="product" onclick="addCart(${p.id})"><b>${esc(p.name)}</b><div class="muted">${esc(p.cat)} • ${esc(p.barcode)}</div><div class="price">${money(p.sell)} جنيه</div><div class="muted">المتاح: ${p.qty}</div></button>`).join('')||'<div class="empty">لا توجد أصناف</div>'}
function renderCart(){let total=0;$('cart').innerHTML=cart.map(x=>{let p=products.find(p=>p.id==x.id),v=p.sell*x.qty;total+=v;return `<div class="cart-row"><div><b>${esc(p.name)}</b><div class="muted">${money(p.sell)} × ${x.qty}</div></div><div class="qty"><button onclick="qty(${p.id},-1)">−</button>${x.qty}<button onclick="qty(${p.id},1)">+</button></div><b>${money(v)}</b><button class="btn danger" onclick="removeCart(${p.id})">×</button></div>`}).join('')||'<div class="empty">السلة فارغة</div>';$('cartTotal').textContent=money(total)}function qty(id,d){let x=cart.find(x=>x.id==id),p=products.find(p=>p.id==id);if(d>0&&x.qty>=p.qty)return toast('الكمية غير كافية');x.qty+=d;if(x.qty<1)removeCart(id);renderCart()}function removeCart(id){cart=cart.filter(x=>x.id!=id);renderCart()}
function checkout(){if(!cart.length)return toast('السلة فارغة');let payment=$('payment').value,customer=$('customerSelect').value,total=0,cost=0,items=[];for(let x of cart){let p=products.find(p=>p.id==x.id);if(!p||x.qty>p.qty)return toast('راجع الكميات');total+=p.sell*x.qty;cost+=p.buy*x.qty;items.push({...x,name:p.name,barcode:p.barcode,sell:p.sell,buy:p.buy});p.qty-=x.qty}sales.unshift({id:Date.now(),date:new Date().toISOString(),total,cost,payment,customer,items});if(customer&&payment==='آجل'){let c=customers.find(x=>x.id===customer);c.balance=(c.balance||0)+total}cart=[];save();renderAll();toast('تم إتمام البيع وتحديث المخزون')}
function addProduct(){let name=$('pName').value.trim(),barcode=$('pBarcode').value.trim();if(!name||!barcode)return toast('الاسم والباركود مطلوبان');if(products.some(p=>p.barcode===barcode))return toast('الباركود مستخدم بالفعل');products.push({id:Date.now(),name,barcode,buy:+$('pBuy').value||0,sell:+$('pSell').value||0,qty:+$('pQty').value||0,min:+$('pMin').value||0,cat:$('pCat').value.trim()||'عام'});save();['pName','pBarcode','pBuy','pSell','pQty','pMin','pCat'].forEach(x=>$(x).value='');renderAll();toast('تم حفظ الصنف')}
function editProduct(id){let p=products.find(x=>x.id==id);openModal('تعديل الصنف',`<div class="form"><input id="mName" class="input" value="${esc(p.name)}"><input id="mBarcode" class="input" value="${esc(p.barcode)}"><input id="mBuy" class="input" type="number" value="${p.buy}"><input id="mSell" class="input" type="number" value="${p.sell}"><input id="mQty" class="input" type="number" value="${p.qty}"><input id="mMin" class="input" type="number" value="${p.min}"><input id="mCat" class="input wide" value="${esc(p.cat)}"><button class="btn primary wide" onclick="updateProduct(${id})">حفظ</button></div>`)}function updateProduct(id){let p=products.find(x=>x.id==id),b=$('mBarcode').value.trim();if(products.some(x=>x.id!=id&&x.barcode===b))return toast('الباركود مستخدم');Object.assign(p,{name:$('mName').value.trim(),barcode:b,buy:+$('mBuy').value||0,sell:+$('mSell').value||0,qty:+$('mQty').value||0,min:+$('mMin').value||0,cat:$('mCat').value.trim()||'عام'});save();closeModal();renderAll()}
function renderInventory(){let q=($('invSearch').value||'').toLowerCase(),a=products.filter(p=>(p.name+' '+p.barcode+' '+p.cat).toLowerCase().includes(q));$('invTable').innerHTML=a.map(p=>`<tr><td><b>${esc(p.name)}</b><div class="muted">${esc(p.cat)}</div></td><td>${esc(p.barcode)}</td><td class="${p.qty<=p.min?'low':''}">${p.qty}</td><td>${money(p.buy)}</td><td>${money(p.sell)}</td><td><button class="btn secondary" onclick="editProduct(${p.id})">تعديل</button> <button class="btn danger" onclick="delProduct(${p.id})">حذف</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد أصناف</td></tr>'}function delProduct(id){if(confirm('حذف الصنف؟')){products=products.filter(p=>p.id!=id);cart=cart.filter(x=>x.id!=id);save();renderAll()}}
function addCustomer(){let n=$('cName').value.trim();if(!n)return toast('اسم العميل مطلوب');customers.push({id:String(Date.now()),name:n,phone:$('cPhone').value.trim(),address:$('cAddress').value.trim(),balance:0});save();['cName','cPhone','cAddress'].forEach(x=>$(x).value='');renderAll();toast('تم حفظ العميل')}function renderCustomers(){$('customerSelect').innerHTML='<option value="">عميل نقدي</option>'+customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('custTable').innerHTML=customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone||'-')}</td><td>${money(c.balance)}</td><td><button class="btn danger" onclick="delCustomer('${c.id}')">حذف</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">لا يوجد عملاء</td></tr>'}function delCustomer(id){customers=customers.filter(c=>c.id!==id);save();renderAll()}
function addExpense(){let n=$('eName').value.trim(),a=+$('eAmount').value||0;if(!n||a<=0)return toast('أدخل البيان والمبلغ');expenses.unshift({id:Date.now(),date:new Date().toISOString(),name:n,amount:a});save();$('eName').value=$('eAmount').value='';renderAll()}function renderAccounts(){let s=sales.reduce((a,x)=>a+x.total,0),c=sales.reduce((a,x)=>a+x.cost,0),e=expenses.reduce((a,x)=>a+x.amount,0);$('salesTotal').textContent=money(s)+' ج';$('costTotal').textContent=money(c)+' ج';$('expenseTotal').textContent=money(e)+' ج';$('profitTotal').textContent=money(s-c-e)+' ج';$('accountLog').innerHTML=[...sales.slice(0,8).map(x=>`<p>بيع <b>${money(x.total)} ج</b></p>`),...expenses.slice(0,5).map(x=>`<p>مصروف ${esc(x.name)} — <b>${money(x.amount)} ج</b></p>`)].join('')||'<div class="empty">لا توجد عمليات</div>'}
function addUser(){let n=$('uName').value.trim(),pass=$('uPass').value;if(!n||!pass)return toast('اسم المستخدم وكلمة المرور مطلوبان');if(users.some(u=>u.name===n))return toast('المستخدم موجود');users.push({id:Date.now(),name:n,role:$('uRole').value,pass});save();$('uName').value=$('uPass').value='';renderUsers();toast('تمت إضافة المستخدم')}
function renderUsers(){$('userTable').innerHTML=users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.role)}</td><td>${u.role==='مدير'?'كل الصلاحيات':u.role==='كاشير'?'POS والعملاء':u.role==='مخزن'?'المخزن':'الحسابات'}</td></tr>`).join('')}
function openModal(t,h){$('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="toolbar"><h3 style="flex:1">${t}</h3><button class="btn secondary" onclick="closeModal()">إغلاق</button></div><hr>${h}</div></div>`}function closeModal(){$('modalRoot').innerHTML=''}function renderAll(){renderProducts();renderCart();renderInventory();renderCustomers();renderAccounts();renderUsers();$('invCount').textContent=products.length;$('stockValue').textContent=money(products.reduce((s,p)=>s+p.buy*p.qty,0));$('lowCount').textContent=products.filter(p=>p.qty<=p.min).length;$('soldCount').textContent=sales.reduce((s,x)=>s+x.items.reduce((a,i)=>a+i.qty,0),0)}
function applyRole(role){const allow={مدير:['pos','inventory','customers','accounts','users'],كاشير:['pos','customers'],مخزن:['inventory'],حسابات:['accounts']}[role]||['pos'];document.querySelectorAll('.nav button').forEach(b=>{b.style.display=allow.includes(b.dataset.page)?'block':'none'});const first=document.querySelector('.nav button[style*="block"]');if(first&&first.dataset.page!=='pos'){first.click()}}
function login(){const n=$('loginUser').value.trim(),p=$('loginPass').value,u=users.find(x=>x.name===n&&x.pass===p);if(!u){$('loginError').textContent='اسم المستخدم أو كلمة المرور غير صحيحة';return}sessionStorage.setItem('fs_session',JSON.stringify({id:u.id,name:u.name,role:u.role}));$('login').classList.add('hidden');$('app').classList.remove('hidden');$('currentUser').textContent=`${u.name} • ${u.role}`;applyRole(u.role);renderAll();$('posBarcode').focus();$('loginError').textContent=''}
function logout(){sessionStorage.removeItem('fs_session');location.reload()}
$('loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('loginUser').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginPass').focus()});
$('posBarcode').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();scan(e.target.value,'pos')}});$('pBarcode').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();scan(e.target.value,'inventory')}});$('posSearch').addEventListener('input',renderProducts);$('invSearch').addEventListener('input',renderInventory);document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(b.dataset.page).classList.remove('hidden');$('pageTitle').textContent=b.textContent.replace(/^\S+\s/,'');if(b.dataset.page==='pos')$('posBarcode').focus()});
const session=JSON.parse(sessionStorage.getItem('fs_session')||'null');if(session){const u=users.find(x=>x.id===session.id);if(u){$('login').classList.add('hidden');$('app').classList.remove('hidden');$('currentUser').textContent=`${u.name} • ${u.role}`;applyRole(u.role)}}renderAll();