/* Five Stars — lossless shell sync with monotonic DB cursor */
(() => {
  'use strict';
  const URL='https://pndoaxhtqzoangffyijx.supabase.co', KEY='sb_publishable_tjcD65pFVq7AqP3WunTZFA_IpslAJz2', TABLE='fs_sync_events';
  const DEVICE='fs_device_v2', CURSOR='fs_cursor_seq_v2', SNAP='fs_snapshot_v4', QUEUE='fs_queue_v4', BOOT='fs_boot_v2', INTERVAL=4000;
  const STORES={fs_products:['product',1,'id'],fs_customers:['customer',1,'id'],fs_suppliers:['supplier',1,'id'],fs_sales:['sale',1,'id'],fs_expenses:['expense',1,'id'],fs_users:['user',1,'id'],fs_held_carts:['held_cart',1,'id'],fs_movements:['movement',1,'id'],fs_receipts:['receipt',1,'id'],fs_categories:['categories',0],fs_settings:['settings',0],fs_active_shift:['active_shift',0],fs_shift_history:['shift_history',1,'id']};
  let db=null,busy=false,initialized=false,cursor=Number(localStorage.getItem(CURSOR)||0)||0; let snap=load(SNAP,{}), queue=load(QUEUE,[]);
  const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}}, save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const dev=()=>{let v=localStorage.getItem(DEVICE);if(!v){v=crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem(DEVICE,v)}return v};
  const st=t=>window.FiveStarsShell?.setStatus?.(t);
  const rows=(k,m)=>{const raw=load(k,m[1]?[]:null);if(!m[1])return {singleton:JSON.stringify(raw)};const o={};(Array.isArray(raw)?raw:[]).forEach((r,i)=>o[String(r?.[m[2]]??`idx-${i}`)]=JSON.stringify(r));return o};
  const take=()=>{const s={};for(const [k,m] of Object.entries(STORES))s[k]=rows(k,m);return s};
  const ek=e=>Object.entries(STORES).find(([,m])=>m[0]===e)?.[0];
  const ev=(entity,id,operation,payload)=>({op_id:`${dev()}:${crypto?.randomUUID?.()||Math.random().toString(36).slice(2)}`,device_id:dev(),entity,entity_id:String(id),operation,payload,client_ts:new Date().toISOString()});
  function collect(force=false){const cur=take();for(const [k,m] of Object.entries(STORES)){const p=snap[k]||{},c=cur[k]||{};for(const [id,txt] of Object.entries(c))if(force||p[id]!==txt)queue.push(ev(m[0],id,'upsert',JSON.parse(txt)));for(const id of Object.keys(p))if(!(id in c))queue.push(ev(m[0],id,'delete',null))}snap=cur;save(SNAP,snap);save(QUEUE,queue)}
  function apply(x){const k=ek(x.entity);if(!k)return;const m=STORES[k];if(!m[1]){if(x.operation==='delete')localStorage.removeItem(k);else save(k,x.payload);return}const old=load(k,[]),a=Array.isArray(old)?old.slice():[],i=a.findIndex(r=>String(r?.[m[2]])===String(x.entity_id));if(x.operation==='delete'){if(i>=0)a.splice(i,1)}else if(i>=0)a[i]=x.payload;else a.unshift(x.payload);save(k,a)}
  async function pull(){if(!db||!navigator.onLine)return 0;const q=db.from(TABLE).select('seq,op_id,device_id,entity,entity_id,operation,payload,client_ts,server_ts').gt('seq',cursor).order('seq',{ascending:true}).limit(1000);const {data,error}=await q;if(error)throw error;if(!data?.length)return 0;let foreign=0;for(const x of data){if(x.device_id!==dev()){apply(x);foreign++}cursor=Math.max(cursor,Number(x.seq)||cursor)}localStorage.setItem(CURSOR,String(cursor));snap=take();save(SNAP,snap);return foreign}
  async function push(){if(!db||!navigator.onLine||!queue.length)return 0;const b=queue.slice(0,100),{error}=await db.from(TABLE).upsert(b,{onConflict:'op_id'});if(error)throw error;queue.splice(0,b.length);save(QUEUE,queue);return b.length}
  async function sync(){if(busy||!db||!navigator.onLine)return;busy=true;try{if(!initialized){initialized=true;const before=cursor;const foreign=await pull();if(cursor===before&&!localStorage.getItem(BOOT)){snap={};save(SNAP,snap);collect(true);localStorage.setItem(BOOT,'1')}else if(foreign)window.FiveStarsShell?.reloadApp?.()}else collect();st(queue.length?`جاري المزامنة • ${queue.length} عملية`:'جاري التحقق…');await push();const foreign=await pull();if(foreign)window.FiveStarsShell?.reloadApp?.();st('متزامن • تلقائي')}catch(e){console.warn('[Five Stars Sync]',e);st(navigator.onLine?'المزامنة مؤجلة • ستعاد تلقائيًا':'بدون إنترنت • العمل المحلي مستمر')}finally{busy=false}}
  async function init(){if(!window.supabase?.createClient){st('خدمة المزامنة غير محملة');return}db=window.supabase.createClient(URL,KEY,{auth:{persistSession:false}});window.FiveStarsSync={syncNow:sync,status:()=>({online:navigator.onLine,queued:queue.length,cursor,deviceId:dev()})};window.addEventListener('online',()=>{st('تم الاتصال • المزامنة تلقائية');sync()});window.addEventListener('offline',()=>st('بدون إنترنت • العمل المحلي مستمر'));await sync();setInterval(sync,INTERVAL)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
